### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy array

In [2]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# 2d and 3d arrays
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# dtype
d = np.array([1,2,3],dtype=float)
print(d)
print(d.dtype)

[1. 2. 3.]
float64


In [6]:
# np.arange

# syntax : np.arange(start,stop,step)
e = np.arange(1,11,2)
print(e)

[1 3 5 7 9]


In [7]:
# with reshape
# syntax : np.arange(start,stop).reshape(rows,cols)
f = np.arange(1,13).reshape(3,4)
print(f)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
# np.zeros and np.ones
ones_array = np.ones((2,3))
zero_array = np.zeros((3,4))
print(ones_array)
print(zero_array)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
# np.random
random_array = np.random.random((2,3))
print(random_array)  

[[0.44604792 0.09423975 0.5271583 ]
 [0.23185554 0.35913379 0.9855733 ]]


In [10]:
# np.linespace
# equaly spaced numbers over a specified interval
# syntax : np.linspace(start,stop,num)
linespace_array = np.linspace(-10,10,10)
print(linespace_array)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [11]:
# identity matrix
identity_matrix = np.identity(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Numpy Attributes

In [12]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
# syntax : np.arange(start,stop).reshape(dim1,dim2,dim3)
a3 = np.arange(8).reshape(2,2,2)

In [13]:
# ndim
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
# shape

print(f"{a1.shape}, {a2.shape}, {a3.shape}")
print(f"a1: {a1}\na2: {a2}\na3: {a3}")


(10,), (3, 4), (2, 2, 2)
a1: [0 1 2 3 4 5 6 7 8 9]
a2: [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
a3: [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [15]:
# size
a1.size, a2.size, a3.size

(10, 12, 8)

In [16]:
# itemsize
a1.itemsize, a2.itemsize, a3.itemsize
# a1 is int32 so 4 bytes, a2 is float64 so 8 bytes, a3 is int32 so 4 bytes

(4, 8, 8)

In [17]:
# dtype
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int64'))

In [18]:
# # astype
# used to change the datatype of an array
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Numpy Array operations

In [19]:
arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(12,24).reshape(3,4)
arr1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
# scalar operations

# airthmetic operations
# here arr1 is a 3x4 matrix and 2 is a scalar
print(arr1 * 2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [21]:
# relational operations
print(arr1 > 5)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [22]:
# vector operations
# arithmetic operations
# here both arr1 and arr2 are 3x4 matrices
print(arr1 + arr2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [23]:
# max and min
print(f"max of arr1: {np.max(arr1)},min of arr1:{np.min(arr1)}")
# row is 1 and col is 0
print(f"max of row1 : {np.max(arr1,axis=0)}")
print(f"max of col1 : {np.max(arr1,axis=1)}")

max of arr1: 11,min of arr1:0
max of row1 : [ 8  9 10 11]
max of col1 : [ 3  7 11]


In [24]:
# sum and prod

print(f"sum of arr1: {np.sum(arr1)}")
print(f"product of arr1: {np.prod(arr1)}")

sum of arr1: 66
product of arr1: 0


In [31]:
# mean 
arr4 = np.arange(1,13).reshape(3,4)
# mean_arr4 = np.mean(arr4,axis=1)
mean_arr4 = np.mean(arr4)
print(f"mean of arr4: {mean_arr4}")

mean of arr4: 6.5


In [33]:
# median
median_arr4 = np.median(arr4)
print(f"median of arr4: {median_arr4}")

median of arr4: 6.5


In [35]:
# standard deviation and varianvce
variance_arr4 = np.var(arr4)
print(f"variance of arr4: {variance_arr4}")

# standard deviation
stddev_arr4 = np.std(arr4)
print(f"standard deviation of arr4: {stddev_arr4}")

variance of arr4: 11.916666666666666
standard deviation of arr4: 3.452052529534663


In [36]:
# trignometry functions (not used much)
print(np.sin(arr4))

[[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825]
 [ 0.41211849 -0.54402111 -0.99999021 -0.53657292]]


In [42]:
# dot products
m1 = np.arange(1,7).reshape(2,3)
m2 = np.arange(6,12).reshape(3,2)
dot_product = np.dot(m1,m2)
print(f"dot product of m1 and m2:\n{dot_product}")


dot product of m1 and m2:
[[ 52  58]
 [124 139]]


In [43]:
# log and exponential functions
print(f"Log of m1\n{np.log(m1)}\nExp of m1\n{np.exp(m1)}")

Log of m1
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
Exp of m1
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [46]:
# round/floor/ceil
random_array = np.random.random((2,3)) * 100
print(f"random array:\n{random_array}")
floored_arr = np.floor(random_array)
rounded_arr = np.round(random_array)
ceiled_arr = np.ceil(random_array)
print(f"floored array:\n{floored_arr}\nrounded array:\n{rounded_arr}\nceiled array:\n{ceiled_arr}")

random array:
[[ 5.12763353  2.92481691 44.99289235]
 [55.54635338 13.56412245 24.76764902]]
floored array:
[[ 5.  2. 44.]
 [55. 13. 24.]]
rounded array:
[[ 5.  3. 45.]
 [56. 14. 25.]]
ceiled array:
[[ 6.  3. 45.]
 [56. 14. 25.]]


### Indexing and slicing

In [47]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [48]:
print(a1)
print(a2)
print(a3)


[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [56]:
# find 4 in a2
print(a2[1,0])

4


In [58]:
# find 5 in a3
a3
print(a3[1,0,1])

5


In [60]:
# find 6 in a3
a3
print(a3[1,1,0])

6


In [62]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
# print 2,3,4
print(a1[2:5])

[2 3 4]


In [64]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
# print first row
print(a2[0,:])

[0 1 2 3]


In [77]:
# print 3rd col
print(a2[:,-1])

[ 3  7 11]


In [79]:
# print 1st col and 2nd row from a2 
print(a2[:,0],a2[1,:])

[0 4 8] [4 5 6 7]


In [84]:
# find 123,567
print(a2[0:2,1:])

[[1 2 3]
 [5 6 7]]


In [89]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [90]:
# print 2nd row in 2nd matrix
print(a3[2,1,:])

[21 22 23]


In [93]:
# print 1st column of 1st and 3rd matrix with step 2

print(a3[::2,0,::2])

[[ 0  2]
 [18 20]]


### Iteration

In [94]:
a2 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


### Reshaping

In [ ]:
# reshape
a1 = np.arange(12)
print(a1)
a2 = a1.reshape(3,4)
print(a2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [100]:
# transpose
# print(np.transpose(a2))
print(a2.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [101]:
# ravel - flattening the array
a2_ravel = a2.ravel()
print(a2_ravel)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


### Stacking

In [105]:
a4 = np.arange(16).reshape(4,4)
a5 = np.arange(16,32).reshape(4,4)
print(a4)
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [106]:
# hstack
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 24, 25, 26, 27],
       [12, 13, 14, 15, 28, 29, 30, 31]])

In [109]:
# vstack
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

### Splitting

In [113]:
# hsplit
a6, a7 = np.hsplit(a4,2)

In [115]:
print(a7.shape)
print(a6)

(4, 2)
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [117]:
print(a5.shape)
print(np.vsplit(a5,2))

(4, 4)
[array([[16, 17, 18, 19],
       [20, 21, 22, 23]]), array([[24, 25, 26, 27],
       [28, 29, 30, 31]])]
